kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ template "fullname" . }}"
  namespace: "{{ .Values.environment }}"
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
{{- $path := printf "%s/%s" .Values.environment .Values.genesisFileName }}
{{ (.Files.Glob $path).AsConfig | indent 2 }}